@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!$domains_root_path = ..

!define actors $domains_root_path/shared/actors
!define systems $domains_root_path/shared/systems
!define external_systems $domains_root_path/shared/external-systems

!include actors/persons.iuml!client
!include systems/systems.iuml!warm_home
!include external_systems/devices.iuml!heater


skinparam wrapWidth 500
LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

title
    <b>Тёплый дом</b>
    <i>Приложение по управлению умным домом (SaaS)</i>
end title

Rel_D(client, warm_home, "Управляет домом", "REST API")
Rel_R(warm_home, heater, "Управляет устройством", "REST API")

@enduml
